### ISSUE TITLE
[tool.poetry.scripts]

### ISSUE THREAD

**Issue by mateusoliveira43** [mateusoliveira43/docky#20]
Add option to run Docky as a `[tool.poetry.scripts]`
```
pip install -e .
```

```toml
[tool.poetry.scripts]
docky = "scripts.docky.__main__:CLI"
```
