### ISSUE TITLE
Automatically add CLI to path

### ISSUE THREAD

**Issue by mateusoliveira43** [mateusoliveira43/docky#23]
pre-commit does not have a post-clone stage yet, this snippet would trigger after running `git checkout`
```
- repo: local
    hooks:
    - id: post-checkout-local
      name: Add CLI to path
      entry: pip install -e ./
      always_run: true
      stages: [post-checkout]
```
